# Generated by Django 4.0.4 on 2022-04-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
