# Generated by Django 4.0.4 on 2022-04-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcounter',
            old_name='receiver_token',
            new_name='receiver_email',
        ),
        migrations.RenameField(
            model_name='chatcounter',
            old_name='sender_token',
            new_name='sender_email',
        ),
    ]
