# Generated by Django 4.0.4 on 2022-04-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_user1_email_chatroom_user2_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user1_email',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user2_email',
        ),
    ]
